# -*- coding: utf-8 -*-
"""tfm_analisis_bancario_españa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tLUbAihazCKoqfaVRKpDNqYHmrpmeZy9
"""

# instalar librerías
!pip install yfinance requests pandas openpyxl

# Importar librerías
import pandas as pd
import numpy as np
import requests
import yfinance as yf

# Definir los bancos y tickers

bancos = {
    "Banco Santander": "SAN.MC",
    "BBVA": "BBVA.MC",
    "CaixaBank": "CABK.MC",
    "Banco Sabadell": "SAB.MC",
    "Bankinter": "BKT.MC"
}

"""# Descargar precios de mercado"""

# Descargar precios de mercado

start_date = "2007-01-01"
end_date = "2025-12-31"

market_data = []

for banco, ticker in bancos.items():
    df = yf.download(ticker, start=start_date, end=end_date, auto_adjust=True, progress=False)

    if df.empty:
        print(f"No se pudieron descargar datos para {banco} ({ticker})")
        continue

    # Aplana el MultiIndex de columnas
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    df = df.reset_index()
    df["banco"] = banco
    df["ticker"] = ticker
    df["año"] = df["Date"].dt.year

    df["daily_return"] = df["Close"].pct_change() # (valor_hoy - valor_ayer) / valor_ayer

    annual = df.groupby(["banco", "ticker", "año"]).agg(  # agrupamos poer banco y año
        precio_accion_medio_anual=("Close", "mean"),  # promedio de los ~250 cierres (en finanzas se mide en días de mercado, no días naturales)
        precio_accion_cierre_anual=("Close", "last"),  # último cierre del año
        precio_accion_primer_dia_negociacion=("Close", "first"), # primer cierre del año
        volatilidad_anual=("daily_return", lambda x: x.std() * np.sqrt(252))
    ).reset_index()

    annual["rentabilidad_anual_accion"] = (
        annual["precio_accion_cierre_anual"] - annual["precio_accion_primer_dia_negociacion"]
    ) / annual["precio_accion_primer_dia_negociacion"]

    market_data.append(annual)

df_market = pd.concat(market_data, ignore_index=True)
df_market.head()

"""# Descargar datos macro de World Bank

Vamos a descargas los datos macroeconómicos de España desde el Banco Mundial (World Bank) y los vamos a unir en una sola tabla. Es el equivalente a lo que hicimos con Yahoo Finance, pero en lugar de precios de bolsa, son indicadores económicos del país.
"""

def world_bank_indicator(country, indicator):
    url = f"https://api.worldbank.org/v2/country/{country}/indicator/{indicator}?format=json&per_page=200"  #API publica gratuita
    response = requests.get(url)
    data = response.json()

    if len(data) < 2:
        return pd.DataFrame()

    records = data[1]
    df = pd.DataFrame(records)[["date", "value"]]
    df = df.rename(columns={"date": "año", "value": indicator})
    df["año"] = pd.to_numeric(df["año"], errors="coerce")
    return df

# Definimos años
año_min, año_max = 2007, 2025

# Indicadores
# PIB crecimiento (% anual)
df_gdp = world_bank_indicator("ESP", "NY.GDP.MKTP.KD.ZG")

# Inflación, precios al consumidor (% anual)
df_inflation = world_bank_indicator("ESP", "FP.CPI.TOTL.ZG")

# Desempleo total (% de la población activa total)
df_unemployment = world_bank_indicator("ESP", "SL.UEM.TOTL.ZS")

# Filtrar por rango de años
df_gdp          = df_gdp[df_gdp["año"].between(año_min, año_max)]
df_inflation    = df_inflation[df_inflation["año"].between(año_min, año_max)]
df_unemployment = df_unemployment[df_unemployment["año"].between(año_min, año_max)]

# Unir
df_macro = df_gdp.merge(df_inflation, on="año", how="outer")
df_macro = df_macro.merge(df_unemployment, on="año", how="outer")

# Renombrar
df_macro = df_macro.rename(columns={
    "NY.GDP.MKTP.KD.ZG": "PIB_crecimiento",
    "FP.CPI.TOTL.ZG": "inflacion",
    "SL.UEM.TOTL.ZS": "tasa_desempleo"
})

df_macro = df_macro.sort_values("año").reset_index(drop=True)
df_macro.head()

df_macro.tail()

"""# Resumen para memoria — Bloque macroeconómico

## Contexto y objetivo

Se descargaron indicadores macroeconómicos anuales de España desde la API pública del Banco Mundial para el período 2007-2025. El objetivo es tener una tabla de contexto económico del país que más adelante se cruzará con los datos bursátiles de los bancos, para analizar si variables como el PIB, la inflación o el desempleo tienen relación con la rentabilidad y volatilidad de las acciones.

## La función world_bank_indicator

Se creó una función reutilizable que encapsula toda la lógica de llamada a la API:



```
world_bank_indicator(country, indicator)
```

- **`country`** → código de país en formato ISO3 (ej. `"ESP"` para España)
- **`indicator`** → código del indicador del Banco Mundial (ej. `"NY.GDP.MKTP.KD.ZG"`)

La URL que construye tiene el parámetro `per_page=200` para traer todos los años en una sola llamada sin paginación. La API devuelve una lista de dos elementos: `data[0]` son metadatos que se descartan, y `data[1]` es la lista de registros útiles. Si la respuesta no tiene dos elementos, se devuelve un DataFrame vacío como medida de seguridad.

De cada registro JSON solo se extraen dos campos: `date` (el año, que viene como string y se convierte a numérico) y `value` (el dato del indicador). La columna del indicador conserva el código original hasta el renombrado final.

---

### Indicadores descargados

| Variable | Código Banco Mundial | Qué mide |
|---|---|---|
| PIB | `NY.GDP.MKTP.KD.ZG` | Crecimiento económico anual en % |
| Inflación | `FP.CPI.TOTL.ZG` | Variación anual de precios al consumidor en % |
| Desempleo | `SL.UEM.TOTL.ZS` | % de la población activa sin empleo |

---

### Filtrado por rango de años
El Banco Mundial devuelve datos históricos desde los años 60, por lo que es necesario filtrar antes de hacer el merge. Se usan las mismas constantes `AÑO_MIN = 2007` y `AÑO_MAX = 2025` definidas al principio del notebook para el bloque bursátil, garantizando consistencia entre ambas fuentes.

---

### Unión con `merge` outer
Los tres DataFrames se unen secuencialmente por la columna `año` usando `how="outer"`, lo que preserva todos los años aunque algún indicador no tenga dato para ese año (aparece como `NaN`). Esto es importante porque el Banco Mundial puede tener retrasos de 1-2 años en publicar ciertos indicadores como el desempleo.

---

### Resultado final `df_macro`
Una fila por año con tres indicadores macroeconómicos de España:
```
   año   PIB_crecimiento   inflacion   tasa_desempleo
   2007       3.77            2.84          8.23
   2008      -0.76            4.13         11.25
   2009      -3.77           -0.28         17.86    ← crisis financiera
   2013       0.10            1.40         26.09    ← máximo desempleo
   2021       6.40            3.09         14.91    ← rebote post-COVID
   2022       5.78            8.39         13.03    ← inflación disparada
```

## Buenas prácticas aplicadas

* Las constantes de rango temporal (AÑO_MIN, AÑO_MAX) se definen una sola vez al principio del notebook y se reutilizan tanto en el bloque bursátil como en el macroeconómico. Así un cambio de rango afecta a todo el análisis desde un único punto.
* La función world_bank_indicator es genérica y reutilizable para cualquier país e indicador, evitando repetir código de llamada a la API.
* El renombrado de columnas se hace al final, una vez unidos los tres DataFrames, para no interferir con la clave del merge (año).

# Exportación

## Verificación

Vamos a comprobar que el rango temporal cubre 2007-2025, que no haya años vacíos, que los tickers sean correctos y que las columnas numéricas están bien aplicadas.
"""

print(df_market.info())
print(df_macro.info())

print(df_market["año"].min(), df_market["año"].max())
print(df_macro["año"].min(), df_macro["año"].max())

"""**Problema:** Tipos distintos en `año`.



```
df_market  → año es int32
df_macro   → año es int64
```

Pandas puede tener problemas al hacer el merge si los tipos no coinciden. Conviene homogeneizarlos antes:

"""

df_market["año"] = df_market["año"].astype(int)
df_macro["año"]  = df_macro["año"].astype(int)

"""**Exportación:**"""

df_market.to_csv("datos_mercado_anuales.csv", index=False)
df_macro.to_csv("datos_macro_espana.csv", index=False)

print("Archivos guardados:")
print("- datos_mercado_anuales.csv")
print("- datos_macro_espana.csv")

"""**Validaciones:**"""

print("\nAños mercado:", df_market["año"].min(), "-", df_market["año"].max())
print("Años macro:", df_macro["año"].min(), "-", df_macro["año"].max())

print("\nBancos en mercado:")
print(df_market["banco"].unique())

print("\nNulos mercado:")
print(df_market.isnull().sum())

print("\nNulos macro:")
print(df_macro.isnull().sum())

"""Tipos de interés BCE (FRED)"""

!pip install fredapi

# Descargar tipo de interés

from fredapi import Fred

# Sustituye por tu API key
fred = Fred(api_key="e2f07be0e734ee721dc9a6a93c6e62dc") #e2f07be0e734ee721dc9a6a93c6e62dc

# Tipo de interés del BCE (deposit facility rate)
series = fred.get_series("ECBDFR")

df_rates = series.reset_index()
df_rates.columns = ["date", "tipo_interes"]

df_rates["año"] = df_rates["date"].dt.year

# Convertir a anual (media del año)
df_rates_anual = df_rates.groupby("año")["tipo_interes"].mean().reset_index()

df_rates_anual.head()

#definimos años
año_min,año_max=2007,2025

df_rates_anual = df_rates_anual[df_rates_anual["año"].between(año_min, año_max)]
df_rates_anual.head()

# Integramos con el dataset macro

df_macro = df_macro.merge(df_rates_anual, on="año", how="left")
df_macro.head()

"""Se ha incorporado el tipo de interés oficial del Banco Central Europeo como variable clave para analizar su impacto en la rentabilidad bancaria, dado su efecto directo sobre los márgenes de intermediación

# Resumen para memoria — Tipos de interés BCE (FRED)

## Contexto y objetivo

Se añade al dataset macroeconómico el tipo de interés oficial del BCE (deposit facility rate) como variable clave para el análisis bancario. Es la variable más relevante del sector porque afecta directamente a los márgenes de intermediación (diferencia entre lo que los bancos cobran por préstamos y lo que pagan por depósitos), y por tanto al ROE y la rentabilidad general.

## Fuente de datos — FRED

Se usa la API de FRED (Federal Reserve Economic Data), mantenida por la Reserva Federal de St. Louis, que incluye series del BCE y es más accesible que la API oficial del BCE. Requiere registro gratuito en fred.stlouisfed.org y generación de una API key personal.
La serie utilizada es ECBDFR (ECB Deposit Facility Rate), que representa el tipo al que el BCE remunera los depósitos de los bancos comerciales. Es el tipo de referencia más relevante para el negocio bancario y el más usado en análisis académicos y financieros.

## Pipeline de transformación

Los datos vienen en frecuencia diaria, por lo que se aplica el mismo criterio que con los datos bursátiles: se agrupa por año y se calcula la media anual, obteniendo una sola fila por año coherente con el resto del dataset macro.



```
df_rates_anual = df_rates.groupby("año")["tipo_interes"].mean().reset_index()
```

Se integra en `df_macro` mediante un merge left por `año`, conservando todos los años del dataset macro y añadiendo el tipo de interés donde exista.

## Resultado

`df_macro` queda con cinco variables anuales para España / zona euro:


| Variable | Fuente | Qué mide |
|---|---|---|
| PIB_crecimiento | Banco Mundial | Crecimiento económico anual % |
| inflacion | Banco Mundial | Variación precios al consumidor % |
| tasa_desempleo | Banco Mundial | % población activa sin empleo |
| tipo_interes | BCE vía FRED | Tipo depósito BCE, media anual % |


## Por qué es relevante para el TFM

El tipo de interés del BCE es la variable macro con mayor impacto directo en la banca. Permite analizar:

* El efecto de los tipos negativos (2015-2022) sobre la rentabilidad bancaria
* El impacto de la subida brusca de tipos post-2022 sobre márgenes y ROE
* La correlación entre el ciclo de tipos y la cotización bursátil de los bancos
"""

df_market

"""# Cargar dataset Finanzas"""

from google.colab import drive

drive.mount('/content/drive')

df_finanzas = pd.read_excel("/content/drive/MyDrive/TFM/tfm_finance_dashboard/data/raw/bd_finanzas.xlsx")
#df_finanzas["fecha"] = pd.to_datetime(df_finanzas["fecha"])
#df_finanzas["año"] = df_finanzas["fecha"].dt.year

df_finanzas.head()

"""# UNIÓN DE LOS DATASETS"""

print(df_finanzas.columns)
print(df_market.columns)
print(df_macro.columns)

df_finanzas

# Cambio nombre de los bancos. Si es banco santander, poner solo santander

df_market["banco"] = df_market["banco"].str.replace("Banco ", "", regex=False)
df_market

# renombrar
df_finanzas.rename(columns={"empresa": "banco"}, inplace=True)
df_finanzas["banco"] = df_finanzas["banco"].str.replace("Banco ", "", regex=False)
df_finanzas

df_macro

print(df_finanzas["banco"].unique())
print(df_market["banco"].unique())


print(df_finanzas["ticker"].unique())
print(df_market["ticker"].unique())

df_finanzas["ticker"] = df_finanzas["ticker"].astype(str) + ".MC"

#unir datos financieros + mercado

df_master = pd.merge(
    df_finanzas,
    df_market,
    on=["banco", "ticker", "año"],
    how="left"
)

df_master

# añadir datos macro

df_master = pd.merge(
    df_master,
    df_macro,
    on="año",
    how="left"
)
df_master

df_master.head()
df_master.info()

# valores nulos

df_master.isnull().sum()

# duplicados

df_master.duplicated(subset=["banco", "año"]).sum()

# Rango temporal
print(df_master["año"].min(), df_master["año"].max())

df_master.head()

"""**Resultado final:**

banco | ticker | año | variables_financieras | variables_mercado | variables_macro

# CALCULO DE KPIs OFICIAL
"""

import pandas as pd
import numpy as np

# ─────────────────────────────────────────
# 1. CÁLCULO DE KPIs (formato ancho)
# ─────────────────────────────────────────

df_kpis = df_master[["banco", "ticker", "año"]].copy()

# ── Rentabilidad ──────────────────────────
df_kpis["ROE"] = df_master["beneficio_neto"] / df_master["patrimonio_neto"]

df_kpis["ROA"] = df_master["beneficio_neto"] / df_master["activo_total"]

df_kpis["margen_neto_sobre_activo"] = df_master["margen_neto"] / df_master["activo_total"]

df_kpis["rentabilidad_anual_accion"] = df_master["rentabilidad_anual_accion"]

# ── Eficiencia ────────────────────────────
# Ratio de eficiencia: aproximado como 1 - (margen_neto / margen_bruto)
# Cuanto más bajo, más eficiente
df_kpis["ratio_eficiencia"] = 1 - (df_master["margen_neto"] / df_master["margen_bruto"])

# Margen de intereses sobre activo total (NIM aproximado)
df_kpis["NIM"] = df_master["margen_intereses"] / df_master["activo_total"]

# ── Solvencia y riesgo ────────────────────
df_kpis["CET1"] = df_master["ratio_cet1"]

df_kpis["ratio_morosidad"] = df_master["ratio_morosidad"]

df_kpis["coste_riesgo"] = df_master["coste_riesgo"]

# Apalancamiento: activo total / patrimonio neto
df_kpis["apalancamiento"] = df_master["activo_total"] / df_master["patrimonio_neto"]

# Ratio créditos sobre depósitos (LTD: Loan-to-Deposit)
df_kpis["LTD"] = df_master["prestamos_clientela"] / df_master["depositos_clientela"]

# ── Valoración de mercado ─────────────────
df_kpis["volatilidad_anual"] = df_master["volatilidad_anual"]

df_kpis["precio_cierre"] = df_master["precio_accion_cierre_anual"]

print("Dataset de KPIs (formato ancho):")
print(df_kpis.shape)
df_kpis.head()

# ─────────────────────────────────────────
# 2. TRANSFORMACIÓN A FORMATO LARGO (para Power BI)
# ─────────────────────────────────────────

# Definimos la categoría de cada KPI
categorias = {
    "ROE":                        "Rentabilidad",
    "ROA":                        "Rentabilidad",
    "margen_neto_sobre_activo":   "Rentabilidad",
    "rentabilidad_anual_accion":  "Rentabilidad",
    "ratio_eficiencia":           "Eficiencia",
    "NIM":                        "Eficiencia",
    "CET1":                       "Solvencia y Riesgo",
    "ratio_morosidad":            "Solvencia y Riesgo",
    "coste_riesgo":               "Solvencia y Riesgo",
    "apalancamiento":             "Solvencia y Riesgo",
    "LTD":                        "Solvencia y Riesgo",
    "volatilidad_anual":          "Valoración de Mercado",
    "precio_cierre":              "Valoración de Mercado",
}

# Lista de columnas KPI
kpi_cols = list(categorias.keys())

# Transformar a formato largo
df_kpis_largo = df_kpis.melt(
    id_vars=["banco", "ticker", "año"],
    value_vars=kpi_cols,
    var_name="kpi",
    value_name="valor"
)

# Añadir columna de categoría
df_kpis_largo["categoria"] = df_kpis_largo["kpi"].map(categorias)

# Ordenar
df_kpis_largo = df_kpis_largo.sort_values(
    ["banco", "año", "categoria", "kpi"]
).reset_index(drop=True)

print("Dataset de KPIs (formato largo):")
print(df_kpis_largo.shape)
df_kpis_largo.head(20)

# ─────────────────────────────────────────
# 3. EXPORTAR A EXCEL (para Power BI)
# ─────────────────────────────────────────

# Exportamos las dos versiones: ancha (para análisis en Python)
# y larga (para Power BI)

with pd.ExcelWriter("kpis_bancos.xlsx", engine="openpyxl") as writer:
    df_kpis.to_excel(writer, sheet_name="KPIs_ancho", index=False)
    df_kpis_largo.to_excel(writer, sheet_name="KPIs_largo", index=False)
    df_master.to_excel(writer, sheet_name="Master", index=False)

print("Archivo exportado: kpis_bancos.xlsx")

from google.colab import files
files.download("kpis_bancos.xlsx")

"""# 4.3.1. ANÁLISIS EXPLORATORIO Y EVOLUTIVO

"""

# ─────────────────────────────────────────
# 4.3.1. ANÁLISIS EXPLORATORIO Y EVOLUTIVO
# ─────────────────────────────────────────

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

# Configuración general de gráficos
plt.rcParams.update({
    "figure.dpi": 150,
    "figure.facecolor": "white",
    "axes.facecolor": "white",
    "axes.grid": True,
    "grid.alpha": 0.4,
    "font.size": 10,
    "axes.titlesize": 12,
    "axes.labelsize": 10,
    "legend.fontsize": 9,
})

BANCOS_COLORES = {
    "Santander":  "#EC0000",
    "BBVA":       "#004481",
    "CaixaBank":  "#007AB5",
    "Sabadell":   "#0066CC",
    "Bankinter":  "#FF6B00",
}

# ─────────────────────────────────────────
# 1. ESTADÍSTICOS DESCRIPTIVOS
# ─────────────────────────────────────────

kpi_cols = [
    "ROE", "ROA", "margen_neto_sobre_activo",
    "rentabilidad_anual_accion", "ratio_eficiencia", "NIM",
    "CET1", "ratio_morosidad", "coste_riesgo",
    "apalancamiento", "LTD", "volatilidad_anual"
]

# Descriptivos globales
print("=" * 60)
print("ESTADÍSTICOS DESCRIPTIVOS GLOBALES")
print("=" * 60)
desc_global = df_kpis[kpi_cols].describe().T.round(4)
desc_global.columns = ["n", "media", "std", "min", "p25", "mediana", "p75", "max"]
print(desc_global.to_string())

# Descriptivos por banco
print("\n" + "=" * 60)
print("ESTADÍSTICOS DESCRIPTIVOS POR BANCO")
print("=" * 60)

desc_banco = df_kpis.groupby("banco")[kpi_cols].agg(["mean", "std", "min", "max"]).round(4)
print(desc_banco.to_string())

# ─────────────────────────────────────────
# 2. EVOLUCIÓN TEMPORAL DE KPIs PRINCIPALES
# ─────────────────────────────────────────

def plot_evolucion(kpi, titulo, ylabel, formato_y=None, ax=None):
    """Dibuja la evolución temporal de un KPI para los cinco bancos."""
    if ax is None:
        fig, ax = plt.subplots(figsize=(10, 4))

    for banco, color in BANCOS_COLORES.items():
        datos = df_kpis[df_kpis["banco"] == banco].sort_values("año")
        ax.plot(datos["año"], datos[kpi], marker="o", markersize=3,
                label=banco, color=color, linewidth=1.8)

    ax.set_title(titulo)
    ax.set_xlabel("Año")
    ax.set_ylabel(ylabel)
    ax.legend(loc="best", ncol=2)
    ax.set_xticks(range(2007, 2026, 2))

    if formato_y == "pct":
        ax.yaxis.set_major_formatter(mticker.PercentFormatter(xmax=1, decimals=0))
    elif formato_y == "pct_directo":
        ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{x:.1f}%"))

    # Línea vertical crisis 2008 y 2012
    ax.axvline(2008, color="grey", linestyle="--", linewidth=0.8, alpha=0.6)
    ax.axvline(2012, color="grey", linestyle=":",  linewidth=0.8, alpha=0.6)
    ax.axvline(2020, color="grey", linestyle="-.", linewidth=0.8, alpha=0.6)

    return ax

# ── Panel completo de evolución temporal ──

fig, axes = plt.subplots(3, 2, figsize=(14, 14))
fig.suptitle("Evolución temporal de KPIs principales (2007–2025)",
             fontsize=14, fontweight="bold", y=1.01)

plot_evolucion("ROE",             "Rentabilidad sobre recursos propios (ROE)",
               "ROE",             "pct",          axes[0, 0])
plot_evolucion("ROA",             "Rentabilidad sobre activos (ROA)",
               "ROA",             "pct",          axes[0, 1])
plot_evolucion("NIM",             "Margen de intereses neto (NIM)",
               "NIM",             "pct",          axes[1, 0])
plot_evolucion("ratio_eficiencia","Ratio de eficiencia",
               "Ratio",           "pct",          axes[1, 1])
plot_evolucion("ratio_morosidad", "Ratio de morosidad (NPL)",
               "NPL (%)",         "pct_directo",  axes[2, 0])
plot_evolucion("CET1",            "Ratio CET1 fully loaded",
               "CET1 (%)",        "pct_directo",  axes[2, 1])

plt.tight_layout()
plt.savefig("evolucion_kpis_principales.png", bbox_inches="tight")
plt.show()
print("Gráfico guardado: evolucion_kpis_principales.png")

# ── Panel de solvencia y riesgo ──

fig, axes = plt.subplots(1, 3, figsize=(16, 4))
fig.suptitle("Solvencia y riesgo (2007–2025)",
             fontsize=13, fontweight="bold")

plot_evolucion("CET1",         "CET1 fully loaded (%)",
               "CET1 (%)",     "pct_directo", axes[0])
plot_evolucion("ratio_morosidad", "Ratio de morosidad (NPL)",
               "NPL (%)",      "pct_directo", axes[1])
plot_evolucion("coste_riesgo", "Coste del riesgo de crédito",
               "CoR (%)",      "pct_directo", axes[2])

plt.tight_layout()
plt.savefig("evolucion_solvencia_riesgo.png", bbox_inches="tight")
plt.show()

# ── Panel de mercado ──

fig, axes = plt.subplots(1, 2, figsize=(14, 4))
fig.suptitle("Valoración de mercado (2007–2025)",
             fontsize=13, fontweight="bold")

plot_evolucion("rentabilidad_anual_accion", "Rentabilidad anual de la acción",
               "Rentabilidad",              "pct",  axes[0])
plot_evolucion("volatilidad_anual",         "Volatilidad anual",
               "Volatilidad",               "pct",  axes[1])

plt.tight_layout()
plt.savefig("evolucion_mercado.png", bbox_inches="tight")
plt.show()

# ─────────────────────────────────────────
# 3. COMPARATIVA ENTRE ENTIDADES
# ─────────────────────────────────────────

# Media histórica de cada KPI por banco (ranking)

kpis_ranking = ["ROE", "ROA", "ratio_eficiencia", "NIM",
                "CET1", "ratio_morosidad", "coste_riesgo", "LTD"]

df_ranking = df_kpis.groupby("banco")[kpis_ranking].mean().round(4)

print("=" * 60)
print("MEDIA HISTÓRICA POR BANCO (2007–2025)")
print("=" * 60)
print(df_ranking.to_string())

# Heatmap de medias históricas normalizadas

# Normalizamos entre 0 y 1 para poder comparar KPIs en distintas escalas
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_ranking_norm = pd.DataFrame(
    scaler.fit_transform(df_ranking),
    index=df_ranking.index,
    columns=df_ranking.columns
)

# Para ratio_eficiencia, ratio_morosidad y coste_riesgo invertimos la escala
# porque valores más bajos son mejores
for col in ["ratio_eficiencia", "ratio_morosidad", "coste_riesgo"]:
    df_ranking_norm[col] = 1 - df_ranking_norm[col]

fig, ax = plt.subplots(figsize=(11, 4))
sns.heatmap(
    df_ranking_norm,
    annot=df_ranking.round(3),   # muestra el valor original
    fmt=".3f",
    cmap="RdYlGn",
    linewidths=0.5,
    ax=ax,
    cbar_kws={"label": "Puntuación normalizada (mayor = mejor)"}
)
ax.set_title("Comparativa de KPIs por entidad — media histórica 2007–2025\n"
             "(color: verde = mejor desempeño relativo, rojo = peor)",
             fontsize=11)
ax.set_xlabel("")
ax.set_ylabel("")
plt.tight_layout()
plt.savefig("heatmap_comparativa_bancos.png", bbox_inches="tight")
plt.show()
print("Gráfico guardado: heatmap_comparativa_bancos.png")

# ─────────────────────────────────────────
# 4. MATRIZ DE CORRELACIÓN
# KPIs vs. variables macroeconómicas
# ─────────────────────────────────────────

# Unimos KPIs con variables macro
kpis_para_corr = ["ROE", "ROA", "NIM", "ratio_eficiencia",
                  "ratio_morosidad", "coste_riesgo", "CET1",
                  "rentabilidad_anual_accion", "volatilidad_anual"]

macro_vars = ["PIB_crecimiento", "inflacion", "tasa_desempleo", "tipo_interes"]

df_corr_input = df_kpis[["banco", "año"] + kpis_para_corr].merge(
    df_master[["banco", "año"] + macro_vars],
    on=["banco", "año"],
    how="left"
).dropna()

corr_matrix = df_corr_input[kpis_para_corr + macro_vars].corr().round(2)

# Submatriz: KPIs vs macro únicamente
corr_kpi_macro = corr_matrix.loc[kpis_para_corr, macro_vars]

print("=" * 60)
print("CORRELACIÓN ENTRE KPIs Y VARIABLES MACROECONÓMICAS")
print("=" * 60)
print(corr_kpi_macro.to_string())

# Heatmap de correlación KPIs vs macro

fig, ax = plt.subplots(figsize=(8, 6))
sns.heatmap(
    corr_kpi_macro,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    linewidths=0.5,
    ax=ax,
    vmin=-1, vmax=1
)
ax.set_title("Correlación entre KPIs bancarios y variables macroeconómicas\n"
             "(Coeficiente de correlación de Pearson, 2007–2025)",
             fontsize=11)
ax.set_xlabel("Variables macroeconómicas")
ax.set_ylabel("KPIs")
plt.tight_layout()
plt.savefig("correlacion_kpis_macro.png", bbox_inches="tight")
plt.show()
print("Gráfico guardado: correlacion_kpis_macro.png")

# ─────────────────────────────────────────
# 5. RESUMEN DE HALLAZGOS POR PERÍODO
# ─────────────────────────────────────────

# Definimos los períodos del ciclo económico
periodos = {
    "Crisis financiera (2007–2009)":      (2007, 2009),
    "Crisis deuda soberana (2010–2013)":  (2010, 2013),
    "Recuperación (2014–2019)":           (2014, 2019),
    "COVID-19 (2020–2021)":               (2020, 2021),
    "Normalización tipos (2022–2025)":    (2022, 2025),
}

kpis_resumen = ["ROE", "ROA", "ratio_morosidad", "coste_riesgo", "CET1"]

print("=" * 70)
print("MEDIA DE KPIs PRINCIPALES POR PERÍODO Y BANCO")
print("=" * 70)

for periodo, (año_ini, año_fin) in periodos.items():
    print(f"\n{'─'*70}")
    print(f"  {periodo}")
    print(f"{'─'*70}")
    mask = df_kpis["año"].between(año_ini, año_fin)
    resumen = df_kpis[mask].groupby("banco")[kpis_resumen].mean().round(4)
    print(resumen.to_string())

"""# 4.3.2. ANÁLISIS DE SENSIBILIDAD MACROECONÓMICA"""

# ─────────────────────────────────────────
# 4.3.2. ANÁLISIS DE SENSIBILIDAD MACROECONÓMICA
# Regresiones de panel con efectos fijos
# ─────────────────────────────────────────

!pip install linearmodels -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import warnings
warnings.filterwarnings("ignore")

from linearmodels.panel import PanelOLS, RandomEffects
from linearmodels.panel import compare
import statsmodels.api as sm

# ─────────────────────────────────────────
# 1. PREPARACIÓN DEL DATASET DE PANEL
# ─────────────────────────────────────────

# Variables dependientes (KPIs)
kpis_dependientes = {
    "ROE":              "Rentabilidad sobre recursos propios",
    "ROA":              "Rentabilidad sobre activos",
    "ratio_morosidad":  "Ratio de morosidad (NPL)",
    "coste_riesgo":     "Coste del riesgo de crédito",
}

# Variables independientes (macro)
macro_vars = ["PIB_crecimiento", "inflacion", "tasa_desempleo", "tipo_interes"]

# Construimos el dataset de panel uniendo KPIs y macro
df_panel = df_kpis[["banco", "año"] + list(kpis_dependientes.keys())].merge(
    df_master[["banco", "año"] + macro_vars],
    on=["banco", "año"],
    how="left"
).dropna()

print(f"Observaciones disponibles para el panel: {len(df_panel)}")
print(f"Entidades: {df_panel['banco'].nunique()}")
print(f"Período: {df_panel['año'].min()} – {df_panel['año'].max()}")
print(f"\nObservaciones por banco:")
print(df_panel.groupby("banco").size())

# Establecemos el índice de panel: (entidad, tiempo)
df_panel = df_panel.set_index(["banco", "año"])

print("\nEstructura del panel:")
print(df_panel.info())

# ─────────────────────────────────────────
# 2. REGRESIONES DE PANEL CON EFECTOS FIJOS
# (solo efectos fijos, RE no es viable con este panel pequeño)
# ─────────────────────────────────────────

resultados_fe = {}

for kpi, descripcion in kpis_dependientes.items():
    print(f"\n{'='*60}")
    print(f"Variable dependiente: {descripcion} ({kpi})")
    print(f"{'='*60}")

    modelo_fe = PanelOLS(
        dependent=df_panel[kpi],
        exog=df_panel[macro_vars],
        entity_effects=True,
        time_effects=False
    )
    res_fe = modelo_fe.fit(cov_type="clustered", cluster_entity=True)
    resultados_fe[kpi] = res_fe

    print("\n── Efectos Fijos ──")
    print(res_fe.summary.tables[1])
    print(f"R² within:  {res_fe.rsquared_within:.4f}")
    print(f"R² overall: {res_fe.rsquared_overall:.4f}")
    print(f"F-stat:     {res_fe.f_statistic.stat:.4f}  "
          f"p-valor: {res_fe.f_statistic.pval:.4f}")

# ─────────────────────────────────────────
# 3. JUSTIFICACIÓN DE EFECTOS FIJOS
# Test F de significancia conjunta de los efectos individuales
# H0: todos los efectos fijos son cero (OLS sería suficiente)
# H1: al menos un efecto fijo es distinto de cero (FE necesario)
# ─────────────────────────────────────────

print("\n" + "="*60)
print("TEST F — Significancia de los efectos fijos por entidad")
print("="*60)
print("H0: efectos individuales = 0 → OLS sería suficiente")
print("H1: efectos individuales ≠ 0 → FE es necesario")
print("-"*60)

for kpi, descripcion in kpis_dependientes.items():
    res = resultados_fe[kpi]
    # El F-test de efectos fijos está en el summary
    try:
        f_stat = res.f_statistic_robust.stat
        f_pval = res.f_statistic_robust.pval
    except:
        f_stat = res.f_statistic.stat
        f_pval = res.f_statistic.pval

    conclusion = "FE justificado (rechaza H0)" if f_pval < 0.05 \
                 else "OLS podría ser suficiente"

    print(f"\n{descripcion} ({kpi}):")
    print(f"  F-estadístico: {f_stat:.4f}  |  p-valor: {f_pval:.4f}")
    print(f"  Conclusión: {conclusion}")

# ─────────────────────────────────────────
# 4. TABLA RESUMEN DE COEFICIENTES
# ─────────────────────────────────────────

print("\n" + "="*70)
print("RESUMEN DE COEFICIENTES — EFECTOS FIJOS")
print("Formato: coeficiente (p-valor) | *** p<0.01, ** p<0.05, * p<0.10")
print("="*70)

def significancia(pval):
    if pval < 0.01:  return "***"
    elif pval < 0.05: return "**"
    elif pval < 0.10: return "*"
    else:             return ""

resumen_coefs = []

for kpi in kpis_dependientes.keys():
    res = resultados_fe[kpi]
    fila = {"KPI": kpi}
    for var in macro_vars:
        coef = res.params[var]
        pval = res.pvalues[var]
        sig  = significancia(pval)
        fila[var] = f"{coef:.4f}{sig}"
    fila["R²_within"]  = f"{res.rsquared_within:.3f}"
    fila["R²_overall"] = f"{res.rsquared_overall:.3f}"
    fila["N"]          = int(res.nobs)
    resumen_coefs.append(fila)

df_resumen = pd.DataFrame(resumen_coefs).set_index("KPI")
print(df_resumen.to_string())

# ─────────────────────────────────────────
# 5. VISUALIZACIÓN DE COEFICIENTES
# Gráfico de coeficientes con intervalos de confianza al 95%
# ─────────────────────────────────────────

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle("Coeficientes de regresión de panel (efectos fijos)\n"
             "Impacto de variables macroeconómicas sobre KPIs bancarios",
             fontsize=13, fontweight="bold")

axes_flat = axes.flatten()
colores_vars = {
    "PIB_crecimiento": "#2196F3",
    "inflacion":       "#4CAF50",
    "tasa_desempleo":  "#F44336",
    "tipo_interes":    "#FF9800"
}

for idx, (kpi, descripcion) in enumerate(kpis_dependientes.items()):
    ax = axes_flat[idx]
    res = resultados_fe[kpi]

    coefs  = res.params[macro_vars].values
    errors = res.std_errors[macro_vars].values * 1.96  # IC 95%
    pvals  = res.pvalues[macro_vars].values

    x_pos = np.arange(len(macro_vars))
    colores = [colores_vars[v] for v in macro_vars]

    bars = ax.bar(x_pos, coefs, color=colores, alpha=0.8, width=0.5)
    ax.errorbar(x_pos, coefs, yerr=errors, fmt="none",
                color="black", capsize=5, linewidth=1.5)

    # Añadir asteriscos de significancia
    for i, (coef, pval) in enumerate(zip(coefs, pvals)):
        sig = significancia(pval)
        if sig:
            offset = max(abs(coef), errors[i]) * 0.1
            y_pos  = coef + errors[i] + offset if coef >= 0 else coef - errors[i] - offset
            ax.text(i, y_pos, sig, ha="center", va="bottom" if coef >= 0 else "top",
                    fontsize=12, fontweight="bold")

    ax.axhline(0, color="black", linewidth=0.8, linestyle="--")
    ax.set_title(descripcion, fontsize=10, fontweight="bold")
    ax.set_xticks(x_pos)
    ax.set_xticklabels(["PIB", "Inflación", "Desempleo", "Tipo interés"],
                       fontsize=9)
    ax.set_ylabel("Coeficiente")

    # Leyenda de R²
    ax.text(0.98, 0.02,
            f"R² within = {res.rsquared_within:.3f}\nN = {int(res.nobs)}",
            transform=ax.transAxes, ha="right", va="bottom",
            fontsize=8, bbox=dict(boxstyle="round", facecolor="white", alpha=0.8))

# Leyenda global
parches = [mpatches.Patch(color=c, label=v)
           for v, c in colores_vars.items()]
fig.legend(handles=parches, loc="lower center", ncol=4,
           bbox_to_anchor=(0.5, -0.02), fontsize=9)

plt.tight_layout()
plt.savefig("coeficientes_panel_macro.png", bbox_inches="tight")
plt.show()
print("Gráfico guardado: coeficientes_panel_macro.png")

# ─────────────────────────────────────────
# 6. ANÁLISIS POR ESCENARIOS MACRO
# Valores medios de KPIs en diferentes regímenes de tipos
# ─────────────────────────────────────────

# Clasificamos cada año en régimen de tipos
def clasificar_tipo(t):
    if t < 0:    return "Tipos negativos (<0%)"
    elif t < 1:  return "Tipos bajos (0–1%)"
    elif t < 3:  return "Tipos medios (1–3%)"
    else:        return "Tipos altos (>3%)"

df_escenarios = df_kpis[["banco", "año"] + list(kpis_dependientes.keys())].merge(
    df_master[["banco", "año", "tipo_interes", "tasa_desempleo"]],
    on=["banco", "año"], how="left"
).dropna()

df_escenarios["regimen_tipos"] = df_escenarios["tipo_interes"].apply(clasificar_tipo)

orden_regimen = [
    "Tipos negativos (<0%)",
    "Tipos bajos (0–1%)",
    "Tipos medios (1–3%)",
    "Tipos altos (>3%)"
]

print("\n" + "="*70)
print("MEDIA DE KPIs POR RÉGIMEN DE TIPOS DE INTERÉS")
print("="*70)

resumen_regimen = df_escenarios.groupby("regimen_tipos")[
    list(kpis_dependientes.keys())
].mean().reindex(orden_regimen).round(4)

print(resumen_regimen.to_string())

# Gráfico
fig, axes = plt.subplots(1, 4, figsize=(16, 5))
fig.suptitle("Media de KPIs por régimen de tipos de interés",
             fontsize=12, fontweight="bold")

colores_regimen = ["#1565C0", "#42A5F5", "#FFA726", "#E53935"]

for idx, (kpi, descripcion) in enumerate(kpis_dependientes.items()):
    ax = axes[idx]
    valores = resumen_regimen[kpi].values
    ax.bar(range(len(orden_regimen)), valores,
           color=colores_regimen, alpha=0.85, width=0.6)
    ax.set_title(descripcion, fontsize=9, fontweight="bold")
    ax.set_xticks(range(len(orden_regimen)))
    ax.set_xticklabels(["Neg.", "Bajos\n(0-1%)", "Medios\n(1-3%)", "Altos\n(>3%)"],
                       fontsize=8)
    ax.axhline(0, color="black", linewidth=0.5)

plt.tight_layout()
plt.savefig("kpis_por_regimen_tipos.png", bbox_inches="tight")
plt.show()
print("Gráfico guardado: kpis_por_regimen_tipos.png")